### ISSUE TITLE
Multiplayer OOS

### ISSUE THREAD

**Issue by vevionez** [codereversing/aommaphack#1]
Pretty sure it won't work for multiplayer due to OOS issues. (Tried it on non-steam version and indeed got OOS when enabling it in multiplayer)

**Comment by codereversing** [comment]
Was the multiplayer played through LAN on the base game? This was tested on Voobly's multiplayer, which uses the base version of the game, but a modified .exe, and also on Steam. I did not try regular LAN through the aomx.exe that ships on the CD version. That's probably the issue here.

**Comment by vevionez** [comment]
I actually tried it with your "injector", and it worked. Seems like it had something to do with the injector I used (Extreme Injector). Was on voobly multiplayer through lan btw.

**Comment by codereversing** [comment]
Yeah, you need to use the injector that comes with the hack since that puts the keyboard hook in place.
